### ISSUE TITLE
wildcard permissions in the permissions.yml down't work

### ISSUE THREAD

**Issue by RedstoneFuture** [LuckPerms/LuckPerms#3199]
### Description

With using of LuckPerms I can't use wildcards in the `permissions.yml`. Normal permissions are usable.

- The LuckPerms config option `apply-wildcards:` is activated.
- Tested with storage type H2 and mysql.
- I tested the LuckPerms config option `enable-ops:`, but the options haven't an impact of this behavior.

It this as intended?

In difference, with PEX for example I can use wildcards in the `permissions.yml`.

### Reproduction Steps

Permissions.yml:

```
demo:
       description: test
       default: false
       children:
          fawe.*: true
          worldedit.*: true
          plots.*: true
```

-> `/lp user <user> permission set demo`

### Expected Behaviour

The expected behavior in this case is, that the user with the "demo" permission have the permissions `fawe.*`, `worldedit.*` and `plots.*` too. 

### Server Details

git-Paper-259 (MC: 1.17.1)

### LuckPerms Version

tested with `5.3.74` and `5.3.61`

### Extra Details

I need the `permissions.yml` to get new, often used permission groups. For example, FAWE have hundreds of permissions, and a part of it I would like to collect before I define the LuckPerms permissions.
