### ISSUE TITLE
NoClassDefFoundError: net/luckperms/api/node/Node

### ISSUE THREAD

**Issue by hanatic** [LuckPerms/LuckPerms#3208]
### Description

I was trying to implement the LuckPerms API into my plugin but when it enables, the error attached occurs. I've attached my code in the gist below - it doesn't quote a line reference so I've attached it all.

Code: https://gist.github.com/hanatic/7c2fb0f8bcfbc36d44e85745ef53b5d4

### Reproduction Steps

- Create a plugin which uses the LuckPerms developer API
- Reference the Node interface at some point in your code
- Compile the plugin and add it to your `/plugins` folder of your server
- Restart the server

[ I'm unsure if this is reproducible, it's probably a stupid mistake on my part :) ]

### Expected Behaviour

That the API would enable succesfully and function with the rest of the plugin.

### Server Details

Paper version git-Paper-"e04368045" (MC: 1.16.5)

### LuckPerms Version

v4.3.75

### Logs and Configs

Error: https://gist.github.com/hanatic/da42bb04921a0d5910f026ba5010496e

plugin.yml:
```yml
name: LastLifePlugin
version: '${project.version}'
main: xyz.hanatic.minigames.lastlife.Lastlife
api-version: 1.16
load: STARTUP
authors: [hanatic]
depend: [LuckPerms]
```
