### ISSUE TITLE
`meta-formatting.suffix.duplicates` key being ignored

### ISSUE THREAD

**Issue by JasonHorkles** [LuckPerms/LuckPerms#3590]
### Description

The yaml key `meta-formatting.suffix.duplicates` isn't being used and suffixes are instead using the `meta-formatting.prefix.duplicates` key

### Reproduction Steps

1. Set up prefix and suffix stacking and make the duplicates values for both different
2. Create suffixes with duplicates and notice that it's using the prefix duplicate rules instead

### Expected Behaviour

The suffixes should properly follow their own duplicate rules

### Server Details

git-Paper-404 (MC: 1.19.3) (Git: f9dc371)

### LuckPerms Version

5.4.61

### Logs and Configs

Relevant config portion:
```yaml
meta-formatting:
  prefix:
    format:
      - "highest"
      - "highest_on_track_staff"
      - "highest_on_track_builders"
      - "highest_on_track_donations"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: "&r "
    end-spacer: "&r "
  suffix:
    format:
      - "highest_from_group_default"
      - "highest_on_track_donations"
      - "highest_on_track_staff"
      - "highest"
    duplicates: last-only # notice how this is still using first-only from above
    start-spacer: ""
    middle-spacer: ""
    end-spacer: ""
```

### Extra Details

Using LuckPerms Bungee for the chat stuff, so not sure if it happens on the backend versions too or not
