### ISSUE TITLE
Players with luckperms.autoop can use all luckperms commands even though commands-allow-op is false

### ISSUE THREAD

**Issue by MCMDEV** [LuckPerms/LuckPerms#3899]
### Description

If the `commands-allow-op` config value in LuckPerms is set to `false` AND the config value `auto-op` is `true` AND a player has the permission `luckperms.autoop`, they can use all LuckPerms commands.

### Reproduction Steps

Change the following values according to this in the config.yml
```yaml
apply-bukkit-default-permissions: false
apply-bukkit-child-permissions: false
enable-ops: false
auto-op: true
commands-allow-op: false
```

### Expected Behaviour

A player with just the `luckperms.autoop` permission should not be able to use any LuckPerms commands

### Server Details

git-Paper-392 (MC: 1.20.4)

### LuckPerms Version

v5.4.130

### Extra Details

This might be expected behavior, but if so I believe it really shouldn't be.
