### ISSUE TITLE
Suggestion: %luckperms_in_group% enhancement

### ISSUE THREAD

**Issue by derpykid300** [LuckPerms/LuckPerms#4032]
### Description

Implement a feature to support PAPI placeholder for %luckperms_in_group%

Example:
%luckperms_in_group_{luckperms_meta_guiSelection}%

### Proposed Behaviour

Example (CommandPanels):

```
        has0:
          value0: "no"
          compare0: "%parseother_{{cp-player}}_{luckperms_in_group_{luckperms_meta_guiSelection}%"
          material: black_stained_glass_pane
        has1:
          value0: "yes"
          compare0: "%parseother_{{cp-player}}_{luckperms_in_group_{luckperms_meta_guiSelection}%"
          material: composter
          name: '&fClick to unset &7%luckperms_meta_guiSelection%'
          commands:
          - rightshift= console= lp user %cp-player% parent remove %luckperms_meta_guiSelection%
          - rightshift= console= lp user %cp-player% parent removetemp %luckperms_meta_guiSelection%
          - rightshift= console= lp user %cp-player% parent add default
```

### Extra Details

Why Implement?
\- Useful for configuring the PAPI placeholder for GUI plugin like DeluxeMenus/ComamndPanels and such
