### ISSUE TITLE
issue with Parent & Prefix Stacking

### ISSUE THREAD

**Issue by VouchWasHere** [LuckPerms/LuckPerms#4071]
### Description

Running into an issue, and I believe it may be a bug. 

I have two groups:

```
Trainee:
- prefix.27.&8[&eTrainee&8]&e
- weight.27
- group.default (**as parent**)

Default:
- prefix.1.&8[&7Member&8]&7
- weight.1

LuckPerms config.yml
meta-formatting:
  prefix:
    format:
      - "highest_on_track_staff"
      - "highest_on_track_donator"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: ""
  suffix:
    format:
      - "highest"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: ""
```

**Error:** When I set myself to Trainee, it displays two prefixes "`[Trainee][Member]`", I'm guessing its because of `Default` being a parent for `Trainee` but the main concern is why I'm in one group yet it gives me two prefixes in chat when I'm only in one group (trainee). Is this a bug or?

It should only show `Member`. Any solutions?

### Reproduction Steps

1. Make default group.
2. Make trainee group.
3. Set default as parent of Trainee.
4. Put them into two separate tracks, 'staff' and 'donator'.
5. Set yourself to just one group, trainee.
6. It will for some reason show both prefixes like [Trainee][Member].
7. I tried changing weight and prefix priority but nothing seems to work.

### Expected Behaviour

It should only display one group, because I did /lp user %player% group set Trainee. So the fact they're in one group, but it somehow includes both prefixes.

**What I think is happening**
I think the issue lies in how **Default** is a parent of **Trainee**. So this makes it so they automatically get both prefixes, but I set their group and did not in fact use /lp group add. 

### Server Details

Paper 1.21.4

### LuckPerms Version

v5.4.156

### Extra Details

My discord is `therealaqz` if you need more detail or want an example of how the error looks like.

I am available everyday usually in evenings, BST.
